project_id = "site-promo-brindes"

[api]
enabled = true
port = 56321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 56322
shadow_port = 56320
major_version = 17

[db.pooler]
enabled = false
port = 56329

[studio]
enabled = true
port = 56323

[local_smtp]
enabled = true
port = 56324

[analytics]
enabled = true
port = 56327
backend = "postgres"
